blank_issues_enabled: true
contact_links:
  - name: Help
    url: https://discord.com/invite/goobla
    about: Please join our Discord server for help using Goobla
  - name: Troubleshooting
    url: https://github.com/goobla/goobla/blob/main/docs/faq.md#faq
    about: See the FAQ for common issues and solutions
